name: Bandit Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Bandit
        uses: PyCQA/bandit-action@v1
        with:
          targets: "."
          severity: "HIGH"
          confidence: "HIGH"
